class PriceResolution:

    Day = "Day"
    Hour = "HOUR"
    Hour_2 = "HOUR_2"
    Hour_3 = "HOUR_3"
    Hour_4 = "HOUR_4"
    Minute = "MINUTE"
    Minute_10 = "MINUTE_10"
    Minute_15 = "MINUTE_15"
    Minute_2 = "MINUTE_2"
    Minute_3 = "MINUTE_30"
    Minute_30 = "MINUTE_30"
    Minute_5 = "MINUTE_5"
    Month = "MONTH"
    Second = "SECOND"
    Week = "WEEK"
